FROM mcr.microsoft.com/java/jre:11u2-zulu-alpine
ADD OpcClientApplication-0.1-SNAPSHOT.tar /opt/OpcClientApplication
WORKDIR /opt/OpcClientApplication/OpcClientApplication-0.1-SNAPSHOT/
CMD sh bin/OpcClientApplication